In [3]:
import os 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [4]:
df=pd.read_csv(r'C:\Users\Win 11\Desktop\data science\6-months-data-science\machine learning\bike_project\bike project\Model\clean_bike_data.csv')

In [5]:
df

      Unnamed: 0     price  kms_driven  owner  age  power  brand
0              0   35000.0     17654.0      1  3.0  110.0      1
1              1  119900.0     11000.0      1  4.0  350.0      2
2              2  600000.0       110.0      1  8.0  675.0      3
3              3   65000.0     16329.0      1  4.0  180.0      1
4              4   80000.0     10000.0      1  3.0  150.0      4
...          ...       ...         ...    ...  ...    ...    ...
7301        9362   25000.0     48587.0      1  8.0  150.0      6
7302        9369   35000.0     60000.0      1  9.0  220.0      7
7303        9370  450000.0      3430.0      1  4.0  750.0     15
7304        9371  139000.0     21300.0      1  4.0  400.0      7
7305        9372   80000.0      7127.0      1  5.0  220.0      7

[7306 rows x 7 columns]

In [6]:
x=df.drop(['price', 'Unnamed: 0'], axis=1)
y=df['price']

In [7]:
x

      kms_driven  owner  age  power  brand
0        17654.0      1  3.0  110.0      1
1        11000.0      1  4.0  350.0      2
2          110.0      1  8.0  675.0      3
3        16329.0      1  4.0  180.0      1
4        10000.0      1  3.0  150.0      4
...          ...    ...  ...    ...    ...
7301     48587.0      1  8.0  150.0      6
7302     60000.0      1  9.0  220.0      7
7303      3430.0      1  4.0  750.0     15
7304     21300.0      1  4.0  400.0      7
7305      7127.0      1  5.0  220.0      7

[7306 rows x 5 columns]

In [8]:
y

0        35000.0
1       119900.0
2       600000.0
3        65000.0
4        80000.0
          ...
7301     25000.0
7302     35000.0
7303    450000.0
7304    139000.0
7305     80000.0
Name: price, Length: 7306, dtype: float64

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [10]:
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(5844, 5) (1462, 5) (5844,) (1462,)

## it is a regression problem bcoz in this price is continous numrical data so for regression we use linear regression,decision tree regressor,random forest regressor

In [11]:
## linear regression
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)


from sklearn.metrics import mean_absolute_error,r2_score,mean_squared_error,root_mean_squared_error
print("MAE:",mean_absolute_error(y_test,y_pred))
print("r2_score:",r2_score(y_test,y_pred))
print("MSE:",mean_squared_error(y_test,y_pred))
print("Root mean squared error:",root_mean_squared_error(y_test,y_pred))

MAE: 34413.97382063589
r2_score: 0.7434808272417703
MSE: 4654768586.037079
Root mean squared error: 68225.86449461142

In [12]:
## decision tree regressor
from sklearn.tree import DecisionTreeRegressor
model=DecisionTreeRegressor(random_state=42)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)


from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score,root_mean_squared_error
print("MAE:",mean_absolute_error(y_test,y_pred))
print("MSE:",mean_squared_error(y_test,y_pred))
print("r2_score:",r2_score(y_test,y_pred))
print("Root mean squared error:",root_mean_squared_error(y_test,y_pred))

MAE: 18340.513565891473
MSE: 2628436407.0392346
r2_score: 0.8551497630185418
Root mean squared error: 51268.278760255205

In [13]:
## random forest regressor
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor(n_estimators=100,random_state=42)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)


from sklearn.metrics import mean_absolute_error,mean_squared_error,root_mean_squared_error,r2_score
print("MAE:",mean_absolute_error(y_test,y_pred))
print("MSE:",mean_squared_error(y_test,y_pred))
print("r2_score:",r2_score(y_test,y_pred))
print("Root mean squared error:",root_mean_squared_error(y_test,y_pred))

MAE: 15216.220632511355
MSE: 2134021060.9958599
r2_score: 0.8823964484813731
Root mean squared error: 46195.4658055946

In [14]:
import joblib
joblib.dump(model,"bike_price_model.")

['bike_price_model.']